### ISSUE TITLE
You forgot to mention the required node version in the doc.

### ISSUE THREAD

**Issue by ruyangjin** [gesellix/keepass-node#10]
I tried `npm install` with Node v 4.x, it wasn't successful. Same went for 0.10.x
Now trying 0.12.x ( as the error message in npm install said `requires node >= 0.12` )
What Node version did you use in this project?

Thanks,
Ruyang.

**Comment by gesellix** [comment]
Afaik it should work with v4.x, and 6.x. See https://github.com/gesellix/keepass-node/blob/master/.travis.yml#L4.

Can you send details about the error you get?

**Comment by ruyangjin** [comment]
`
fantdevmac:keepass-node FantDev$ node -v
v4.1.1
fantdevmac:keepass-node FantDev$ npm install
npm WARN peerDependencies The peer dependency lolex@^1.4.0 included from karma-sinon-chai will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency sinon@^1.17.2 included from karma-sinon-chai will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency sinon-chai@^2.8.0 included from karma-sinon-chai will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated dejavu@0.4.8: No
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
-
> dtrace-provider@0.6.0 install /Volumes/R2/Projects/AngularSample/keepass-node/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

/
> phantomjs@1.9.20 install /Volumes/R2/Projects/AngularSample/keepass-node/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-macosx.zip
Saving to /var/folders/11/3l4j3p856cb78s4yllgmjcs40000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...
|
Error making request.
Error: socket hang up
    at createHangUpError (_http_client.js:203:15)
    at TLSSocket.socketOnEnd (_http_client.js:288:23)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)

Please report this full log at https://github.com/Medium/phantomjs

> dejavu@0.4.8 postinstall /Volumes/R2/Projects/AngularSample/keepass-node/node_modules/keepass.io/node_modules/dejavu
> node bin/post_install.js

Saving runtime configuration in /Volumes/R2/Projects/AngularSample/keepass-node/node_modules/keepass.io/.dejavurc

> fsevents@1.0.12 install /Volumes/R2/Projects/AngularSample/keepass-node/node_modules/karma/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build
`

The console is stuck in the last line.

**Comment by ruyangjin** [comment]
$Going to paste again

fantdevmac:keepass-node FantDev$ node -v
v4.1.1
fantdevmac:keepass-node FantDev$ npm install
npm WARN peerDependencies The peer dependency lolex@^1.4.0 included from karma-sinon-chai will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency sinon@^1.17.2 included from karma-sinon-chai will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency sinon-chai@^2.8.0 included from karma-sinon-chai will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated dejavu@0.4.8: No
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
-
> dtrace-provider@0.6.0 install /Volumes/R2/Projects/AngularSample/keepass-node/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

/
> phantomjs@1.9.20 install /Volumes/R2/Projects/AngularSample/keepass-node/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-macosx.zip
Saving to /var/folders/11/3l4j3p856cb78s4yllgmjcs40000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...
|
Error making request.
Error: socket hang up
    at createHangUpError (_http_client.js:203:15)
    at TLSSocket.socketOnEnd (_http_client.js:288:23)
    at emitNone (events.js:72:20)
    at TLSSocket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)

Please report this full log at https://github.com/Medium/phantomjs

> dejavu@0.4.8 postinstall /Volumes/R2/Projects/AngularSample/keepass-node/node_modules/keepass.io/node_modules/dejavu
> node bin/post_install.js

Saving runtime configuration in /Volumes/R2/Projects/AngularSample/keepass-node/node_modules/keepass.io/.dejavurc

> fsevents@1.0.12 install /Volumes/R2/Projects/AngularSample/keepass-node/node_modules/karma/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

**Comment by gesellix** [comment]
This looks like a connection problem. Can you verify if you can download the file from https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-macosx.zip ?
Maybe the issue is only temporary or only in your network?

**Comment by ruyangjin** [comment]
Thanks, Tobias!
I was using China network, it has some limitations. I switched to other
network and I could successfully `npm install` and `npm start`

*The web page is narrow. Is it expected behavior?*

*Thought I don't know what the error messages mean here. ( The ones in the
middle of flow )*

fantdevmac:keepass-node FantDev$ npm install
npm WARN peerDependencies The peer dependency lolex@^1.4.0 included from
karma-sinon-chai will no
npm WARN peerDependencies longer be automatically installed to fulfill the
peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend
on it explicitly.
npm WARN peerDependencies The peer dependency sinon@^1.17.2 included from
karma-sinon-chai will no
npm WARN peerDependencies longer be automatically installed to fulfill the
peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend
on it explicitly.
npm WARN peerDependencies The peer dependency sinon-chai@^2.8.0 included
from karma-sinon-chai will no
npm WARN peerDependencies longer be automatically installed to fulfill the
peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend
on it explicitly.
npm WARN deprecated dejavu@0.4.8: No
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or
higher to avoid a RegExp DoS issue
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please
install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or
higher to avoid a RegExp DoS issue

> dtrace-provider@0.6.0 install
/Volumes/R2/Projects/AngularSample/keepass-node/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js


> phantomjs@1.9.20 install
/Volumes/R2/Projects/AngularSample/keepass-node/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Downloading
https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-macosx.zip
Saving to
/var/folders/11/3l4j3p856cb78s4yllgmjcs40000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...
  [=======================================-] 98%
Received 9187K total.
Extracting zip contents
Removing
/Volumes/R2/Projects/AngularSample/keepass-node/node_modules/phantomjs/lib/phantom
Copying extracted folder
/var/folders/11/3l4j3p856cb78s4yllgmjcs40000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1467020225021/phantomjs-1.9.8-macosx
->
/Volumes/R2/Projects/AngularSample/keepass-node/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at
/Volumes/R2/Projects/AngularSample/keepass-node/node_modules/phantomjs/lib/phantom/bin/phantomjs

> dejavu@0.4.8 postinstall
/Volumes/R2/Projects/AngularSample/keepass-node/node_modules/
keepass.io/node_modules/dejavu
> node bin/post_install.js

Saving runtime configuration in
/Volumes/R2/Projects/AngularSample/keepass-node/node_modules/
keepass.io/.dejavurc

> fsevents@1.0.12 install
/Volumes/R2/Projects/AngularSample/keepass-node/node_modules/karma/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success:
"/Volumes/R2/Projects/AngularSample/keepass-node/node_modules/karma/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node"
is installed via remote

> keepass.io@1.1.3 install
/Volumes/R2/Projects/AngularSample/keepass-node/node_modules/keepass.io
> (node-gyp rebuild 2>&1) || (echo 'DO NOT WORRY ABOUT THESE MESSAGES.
KEEPASS.IO WILL FALLBACK TO SLOWER NODE.JS METHODS, SO THERE ARE NO
LIMITATIONS EXCEPT SLOWER PERFORMANCE.'; exit 0)

  CXX(target) Release/obj.target/kpion/native/kpion.o
In file included from ../native/kpion.cc:8:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in
namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to
'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/chenwang/.node-gyp/4.1.1/include/node/node_buffer.h:31:40: note:
candidate function not viable: no known conversion from 'uint32_t' (aka
'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/chenwang/.node-gyp/4.1.1/include/node/node_buffer.h:43:40: note:
candidate function not viable: 2nd argument ('const char *') would lose
const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/chenwang/.node-gyp/4.1.1/include/node/node_buffer.h:28:40: note:
candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t
length);
                                       ^
/Users/chenwang/.node-gyp/4.1.1/include/node/node_buffer.h:36:40: note:
candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../native/kpion.cc:8:
../node_modules/nan/nan.h:676:12: error: no viable conversion from returned
value of type 'v8::MaybeLocal<v8::Object>' to function return type
'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/chenwang/.node-gyp/4.1.1/include/node/v8.h:210:7: note: candidate
constructor (the implicit copy constructor) not viable: no known conversion
from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for
1st argument
class Local {
      ^
/Users/chenwang/.node-gyp/4.1.1/include/node/v8.h:210:7: note: candidate
constructor (the implicit move constructor) not viable: no known conversion
from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st
argument
/Users/chenwang/.node-gyp/4.1.1/include/node/v8.h:214:13: note: candidate
template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/chenwang/.node-gyp/4.1.1/include/node/v8.h:326:13: note: candidate
template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../native/kpion.cc:8:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace
'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
../native/kpion.cc:11:10: fatal error: 'cryptopp/modes.h' file not found
#include <cryptopp/modes.h>
         ^
6 errors generated.
make: *** [Release/obj.target/kpion/native/kpion.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:200:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/bin/node"
"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd /Volumes/R2/Projects/AngularSample/keepass-node/node_modules/
keepass.io
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
DO NOT WORRY ABOUT THESE MESSAGES. KEEPASS.IO WILL FALLBACK TO SLOWER
NODE.JS METHODS, SO THERE ARE NO LIMITATIONS EXCEPT SLOWER PERFORMANCE.
chai-as-promised@5.3.0 node_modules/chai-as-promised

basic-auth@1.0.4 node_modules/basic-auth

q@1.4.1 node_modules/q

karma-ng-html2js-preprocessor@0.2.2
node_modules/karma-ng-html2js-preprocessor

karma-mocha@0.2.2 node_modules/karma-mocha

node-uuid@1.4.7 node_modules/node-uuid

angular-jwt@0.0.9 node_modules/angular-jwt

crypto-js@3.1.6 node_modules/crypto-js

jsonwebtoken@5.7.0 node_modules/jsonwebtoken
├── ms@0.7.1
└── xtend@4.0.1

require-optional@0.3.0 node_modules/require-optional
└── module-resolve-as-caller@0.1.1 (callsite@1.0.0)

chai@3.5.0 node_modules/chai
├── assertion-error@1.0.2
├── type-detect@1.0.0
└── deep-eql@0.1.3 (type-detect@0.1.1)

compression@1.6.2 node_modules/compression
├── on-headers@1.0.1
├── bytes@2.3.0
├── vary@1.1.0
├── debug@2.2.0 (ms@0.7.1)
├── compressible@2.0.8 (mime-db@1.23.0)
└── accepts@1.3.3 (negotiator@0.6.1, mime-types@2.1.11)

body-parser@1.15.2 node_modules/body-parser
├── content-type@1.0.2
├── bytes@2.4.0
├── depd@1.1.0
├── qs@6.2.0
├── debug@2.2.0 (ms@0.7.1)
├── iconv-lite@0.4.13
├── raw-body@2.1.7 (unpipe@1.0.0)
├── on-finished@2.3.0 (ee-first@1.1.1)
├── http-errors@1.5.0 (setprototypeof@1.0.1, statuses@1.3.0, inherits@2.0.1)
└── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.11)

karma-cli@0.1.2 node_modules/karma-cli
└── resolve@1.1.7

express-jwt@3.4.0 node_modules/express-jwt
├── express-unless@0.3.0
├── async@1.5.2
└── lodash.set@4.2.0 (lodash._baseset@4.3.0)

fs-extra@0.26.7 node_modules/fs-extra
├── path-is-absolute@1.0.0
├── graceful-fs@4.1.4
├── jsonfile@2.3.1
├── klaw@1.3.0
└── rimraf@2.5.2 (glob@7.0.5)

express@4.14.0 node_modules/express
├── escape-html@1.0.3
├── path-to-regexp@0.1.7
├── array-flatten@1.1.1
├── cookie-signature@1.0.6
├── utils-merge@1.0.0
├── methods@1.1.2
├── merge-descriptors@1.0.1
├── encodeurl@1.0.1
├── content-type@1.0.2
├── vary@1.1.0
├── content-disposition@0.5.1
├── etag@1.7.0
├── range-parser@1.2.0
├── fresh@0.3.0
├── serve-static@1.11.1
├── parseurl@1.3.1
├── cookie@0.3.1
├── depd@1.1.0
├── qs@6.2.0
├── debug@2.2.0 (ms@0.7.1)
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.5.0 (unpipe@1.0.0, statuses@1.3.0)
├── proxy-addr@1.1.2 (forwarded@0.1.0, ipaddr.js@1.1.1)
├── send@0.14.1 (destroy@1.0.4, ms@0.7.1, statuses@1.3.0, mime@1.3.4,
http-errors@1.5.0)
├── accepts@1.3.3 (negotiator@0.6.1, mime-types@2.1.11)
└── type-is@1.6.13 (media-typer@0.3.0, mime-types@2.1.11)

supertest@1.2.0 node_modules/supertest
├── methods@1.1.2
└── superagent@1.8.3 (component-emitter@1.2.1, cookiejar@2.0.6,
reduce-component@1.0.1, extend@3.0.0, mime@1.3.4, formidable@1.0.17,
qs@2.3.3, debug@2.2.0, readable-stream@1.0.27-1, form-data@1.0.0-rc3)

clipboard@1.5.12 node_modules/clipboard
├── tiny-emitter@1.0.2
├── select@1.0.6
└── good-listener@1.1.7 (delegate@3.0.1)

mocha@2.5.3 node_modules/mocha
├── escape-string-regexp@1.0.2
├── diff@1.4.0
├── growl@1.9.2
├── supports-color@1.2.0
├── commander@2.3.0
├── to-iso-string@0.0.2
├── debug@2.2.0 (ms@0.7.1)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
└── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)

jws@3.1.3 node_modules/jws
├── jwa@1.1.3 (buffer-equal-constant-time@1.0.1, ecdsa-sig-formatter@1.0.7)
└── base64url@1.0.6 (concat-stream@1.4.10, meow@2.0.0)

hogan.js@3.0.2 node_modules/hogan.js
├── mkdirp@0.3.0
└── nopt@1.0.10 (abbrev@1.0.9)

lcov-result-merger@1.2.0 node_modules/lcov-result-merger
├── vinyl@1.1.1 (clone-stats@0.0.1, replace-ext@0.0.1, clone@1.0.2)
├── through2@2.0.1 (xtend@4.0.1, readable-stream@2.0.6)
└── vinyl-fs@2.4.3 (object-assign@4.1.0, merge-stream@1.0.0, vali-date@1.0.0,
is-valid-glob@0.3.0, graceful-fs@4.1.4, lazystream@1.0.0,
through2-filter@2.0.0, strip-bom-stream@1.0.0, strip-bom@2.0.0,
lodash.isequal@4.2.0, gulp-sourcemaps@1.6.0, readable-stream@2.1.4,
mkdirp@0.5.1, duplexify@3.4.3, glob-stream@5.3.2)

karma-coverage@0.5.5 node_modules/karma-coverage
├── source-map@0.5.6
├── minimatch@3.0.2 (brace-expansion@1.1.5)
└── dateformat@1.0.12 (get-stdin@4.0.1, meow@3.7.0)

sinon-chai@2.8.0 node_modules/sinon-chai

sinon@1.17.4 node_modules/sinon
├── formatio@1.1.1
├── samsam@1.1.2
├── lolex@1.3.2
└── util@0.10.3 (inherits@2.0.1)

lolex@1.5.0 node_modules/lolex

karma-sinon-chai@1.2.0 node_modules/karma-sinon-chai

coveralls@2.11.9 node_modules/coveralls
├── lcov-parse@0.0.6
├── log-driver@1.2.4
├── minimist@1.2.0
├── js-yaml@3.0.1 (esprima@1.0.4, argparse@0.1.16)
└── request@2.67.0 (tunnel-agent@0.4.3, oauth-sign@0.8.2, aws-sign2@0.6.0,
forever-agent@0.6.1, is-typedarray@1.0.0, caseless@0.11.0,
stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0,
tough-cookie@2.2.2, qs@5.2.0, combined-stream@1.0.5, mime-types@2.1.11,
form-data@1.0.0-rc4, hawk@3.1.3, bl@1.0.3, http-signature@1.1.1,
har-validator@2.0.6)

bunyan@1.8.1 node_modules/bunyan
├── safe-json-stringify@1.0.3
├── mv@2.1.1 (ncp@2.0.0, mkdirp@0.5.1, rimraf@2.4.5)
├── moment@2.13.0
└── dtrace-provider@0.6.0 (nan@2.3.5)

karma-phantomjs-launcher@0.2.3 node_modules/karma-phantomjs-launcher
└── lodash@3.10.1

jshint@2.9.2 node_modules/jshint
├── strip-json-comments@1.0.4
├── exit@0.1.2
├── minimatch@2.0.10 (brace-expansion@1.1.5)
├── console-browserify@1.1.0 (date-now@0.1.4)
├── shelljs@0.3.0
├── cli@0.6.6 (glob@3.2.11)
├── htmlparser2@3.8.3 (domelementtype@1.3.0, entities@1.0.0,
domhandler@2.3.0, readable-stream@1.1.14, domutils@1.5.1)
└── lodash@3.7.0

istanbul@0.4.4 node_modules/istanbul
├── abbrev@1.0.9
├── async@1.5.2
├── wordwrap@1.0.0
├── nopt@3.0.6
├── esprima@2.7.2
├── once@1.3.3 (wrappy@1.0.2)
├── supports-color@3.1.2 (has-flag@1.0.0)
├── which@1.2.10 (isexe@1.1.2)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── fileset@0.2.1 (minimatch@2.0.10, glob@5.0.15)
├── resolve@1.1.7
├── escodegen@1.8.0 (estraverse@1.9.3, esutils@2.0.2, optionator@0.8.1,
source-map@0.2.0)
├── js-yaml@3.6.1 (argparse@1.0.7)
└── handlebars@4.0.5 (source-map@0.4.4, optimist@0.6.1, uglify-js@2.6.4)

lodash@4.13.1 node_modules/lodash

googleapis@2.1.7 node_modules/googleapis
├── string-template@0.2.1
├── async@1.5.2
├── gapitoken@0.1.5 (jws@3.0.0)
├── request@2.65.0 (oauth-sign@0.8.2, tunnel-agent@0.4.3, aws-sign2@0.6.0,
forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.5, isstream@0.1.2,
json-stringify-safe@5.0.1, extend@3.0.0, form-data@1.0.0-rc4,
tough-cookie@2.2.2, qs@5.2.0, combined-stream@1.0.5, mime-types@2.1.11,
http-signature@0.11.0, hawk@3.1.3, bl@1.0.3, har-validator@2.0.6)
└── google-auth-library@0.9.8 (async@1.4.2, lodash.noop@3.0.1, jws@3.0.0,
request@2.60.0, gtoken@1.2.1)

phantomjs@1.9.20 node_modules/phantomjs
├── progress@1.1.8
├── kew@0.7.0
├── which@1.2.10 (isexe@1.1.2)
├── request-progress@2.0.1 (throttleit@1.0.0)
├── hasha@2.2.0 (is-stream@1.1.0, pinkie-promise@2.0.1)
├── extract-zip@1.5.0 (debug@0.7.4, mkdirp@0.5.0, yauzl@2.4.1,
concat-stream@1.5.0)
└── request@2.67.0 (tunnel-agent@0.4.3, oauth-sign@0.8.2, aws-sign2@0.6.0,
forever-agent@0.6.1, caseless@0.11.0, is-typedarray@1.0.0,
stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0,
tough-cookie@2.2.2, qs@5.2.0, combined-stream@1.0.5, mime-types@2.1.11,
form-data@1.0.0-rc4, hawk@3.1.3, bl@1.0.3, http-signature@1.1.1,
har-validator@2.0.6)

karma@0.13.22 node_modules/karma
├── rimraf@2.5.2
├── batch@0.5.3
├── di@0.0.1
├── graceful-fs@4.1.4
├── mime@1.3.4
├── colors@1.1.2
├── source-map@0.5.6
├── isbinaryfile@3.0.0
├── http-proxy@1.14.0 (eventemitter3@1.2.0, requires-port@1.0.0)
├── minimatch@3.0.2 (brace-expansion@1.1.5)
├── dom-serialize@2.2.1 (custom-event@1.0.0, void-elements@2.0.1,
extend@3.0.0, ent@2.2.0)
├── useragent@2.1.9 (lru-cache@2.2.4)
├── glob@7.0.5 (path-is-absolute@1.0.0, fs.realpath@1.0.0, inherits@2.0.1,
once@1.3.3, inflight@1.0.5)
├── bluebird@2.10.2
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── connect@3.4.1 (utils-merge@1.0.0, parseurl@1.3.1, debug@2.2.0,
finalhandler@0.4.1)
├── expand-braces@0.1.2 (array-slice@0.2.3, array-unique@0.2.1, braces@0.1.5
)
├── socket.io@1.4.8 (has-binary@0.1.7, debug@2.2.0, socket.io-parser@2.2.6,
socket.io-adapter@0.4.0, engine.io@1.6.11, socket.io-client@1.4.8)
├── log4js@0.6.37 (semver@4.3.6, readable-stream@1.0.34)
├── lodash@3.10.1
├── core-js@2.4.0
└── chokidar@1.6.0 (path-is-absolute@1.0.0, inherits@2.0.1,
glob-parent@2.0.0, async-each@1.0.0, is-glob@2.0.1, is-binary-path@1.0.1,
readdirp@2.0.1, anymatch@1.3.0, fsevents@1.0.12)

keepass.io@1.1.3 node_modules/keepass.io
├── async@1.3.0
├── nan@1.8.4
├── xml2js@0.4.16 (sax@1.2.1, xmlbuilder@4.2.1)
└── dejavu@0.4.8 (amdefine@0.1.1, mout@0.9.1)


On Mon, Jun 27, 2016 at 5:31 PM, Tobias Gesellchen <notifications@github.com
> wrote:

> This looks like a connection problem. Can you verify if you can download
> the file from
> https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-macosx.zip
> ?
> Maybe the issue is only temporary or only in your network?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gesellix/keepass-node/issues/10#issuecomment-228696960>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AI2SnipppEv-SunI8QD38U4L1Lwi2kBMks5qP5htgaJpZM4I-tyk>
> .
>

**Comment by gesellix** [comment]
>Thanks, Tobias!
I was using China network, it has some limitations. I switched to other
network and I could successfully `npm install` and `npm start`

great :-)

> *The web page is narrow. Is it expected behavior?*

You mean the left side with the login? That's intentional. You'll see that with a loaded keepass database and a selected group, you'll get a list of all entries in the main area. That main area should fill the available screen. If not, then you probably found an error.

> *Thought I don't know what the error messages mean here. ( The ones in the
middle of flow )*

Do you mean the messages around those?

````
...
 (node-gyp rebuild 2>&1) || (echo 'DO NOT WORRY ABOUT THESE MESSAGES.
KEEPASS.IO WILL FALLBACK TO SLOWER NODE.JS METHODS, SO THERE ARE NO
LIMITATIONS EXCEPT SLOWER PERFORMANCE.'; exit 0)
...
````

Just like the messages tell you: it's only about some optimisation, but optional. Depending on your environment it'll try to build a more efficient version to handle the whole crypt-stuff. If it doesn't find matching native libraries on your system, it'll fallback to a generic implementation. The only downside is, that it _could_ be a bit slower.
