### ISSUE TITLE
Basic Authentication Doesn't Work

### ISSUE THREAD

**Issue by theminor** [gesellix/keepass-node#8]
In server.js, line 30:

`app.use(express.basicAuth())`

In Express 4, basicAuth() was removed in favor of specific middleware. Perhaps you could implement Passport or some other middleware for authentication. As of now, however, this doesn't work and I get an error with a clean install when I enable Basic Authentication.

When I tried to install middleware of my own (for quick testing, I tried http-auth) and modify this function accordingly, keepass-node asks me to log in and keeps presenting the login box again and again when I enter my username and password.

**Comment by gesellix** [comment]
Thanks for reporting! I added an own middleware to replace the old basic auth, including a way to ignore it when the KeePass specific auth header is provided. This should suppress the login box to appear repeatedly.
